influxdb:
  influxdbout:
    host: "localhost"  # 本地测试数据库
    port: 8086
    username: "admin"
    password: "password"
    database_name: "test_database"

  influxdbin:
    host: "localhost"  # 本地测试数据库
    port: 8086
    username: "admin"
    password: "password"
    database_name: "test_database"

model_name: "MLP"
oa_name: "GDA"
space_id: 5
time_rest: 60  # 测试时使用较短的循环间隔
room_name: "测试机房"

# 简化的测试用设备配置
device_uid:
ac_num_params:
ac_freq_num_params:

predict_result_name_list:
  [
    "ai_predict_it_load",
    "ai_predict_indoor_temp",
    "ai_predict_air_inlet_temp",
    "ai_predict_air_return_temp",
  ]

output_list:
  oa: "ai_energy_saving_suggestions"
  it: "ai_predict_it_load"
  temp: "ai_predict_it_load"
  airin: "ai_predict_air_inlet_temp"
  airreturn: "ai_predict_air_return_temp"
  pue: "ai_predict_pue"
  log: "ai_algorithm_log"
  acc: "ai_algorithm_accuracy"
  iter: "ai_algorithm_iterative"

output_uid:
  ai_predict_it_load: "1"
  ai_predict_indoor_temp: "2"
  ai_predict_air_inlet_temp: "3"
  ai_predict_air_return_temp: "4"

# 简化的测试用uid配置
uid:
  device_uid:
    ac: ["test_ac_1", "test_ac_2", "test_ac_3", "test_ac_4", "test_ac_5", "test_ac_6"]
  
  input_predict_uid: ["test_predict_input_1", "test_predict_input_2"]
  output_predict_uid: ["test_predict_output_1", "test_predict_output_2"]
  
  all_uid: [
    "test_room_temp_1", "test_room_temp_2", "test_room_temp_3",
    "test_ac_temp_1", "test_ac_temp_2", "test_ac_temp_3",
    "test_ac_onoff_1", "test_ac_onoff_2", "test_ac_onoff_3",
    "test_ac_temp_set_1", "test_ac_temp_set_2", "test_ac_temp_set_3"
  ]
  
  input_optimization_uid:
    # 机房温度测点 (3个)
    room_temperature: [
      "test_room_temp_1", 
      "test_room_temp_2", 
      "test_room_temp_3"
    ]
    
    # 空调温度测点 (3个)
    ac_temperature: [
      "test_ac_temp_1",
      "test_ac_temp_2", 
      "test_ac_temp_3"
    ]
    
    # 空调开关设定 (3个)
    ac_onoff_setting: [
      "test_ac_onoff_1",
      "test_ac_onoff_2",
      "test_ac_onoff_3"
    ]
    
    # 空调温度设定 (3个)
    ac_temperature_settings: [
      "test_ac_temp_set_1",
      "test_ac_temp_set_2",
      "test_ac_temp_set_3"
    ]
  
  output_optimization_uid: ["test_output_opt_1", "test_output_opt_2"]
  device_uid_list: []

# 映射关系配置 - 简化版本
mapping:
  # ac_onoff_setting索引到device_uid索引的映射关系
  ac_onoff_to_device: [0, 1, 2]  # 3个ac_onoff对应到3个device
  # ac_temperature_setting是一对一映射
  ac_temp_to_device: [0, 1, 2]   # 3个对3个

name:
  optimization:
    ac_onoff_status_setting: [
      "测试空调1制冷开关",
      "测试空调2制冷开关", 
      "测试空调3制冷开关"
    ]
    ac_temperature_setting: [
      "测试空调1温度设定",
      "测试空调2温度设定",
      "测试空调3温度设定"
    ]

# 边界条件配置
boundary:
  room_temp_lower_boundary: 18
  room_temp_higher_boundary: 28
  ac_temp_lower_boundary: 17
  ac_temp_higher_boundary: 30

# 优化算法配置
optimization:
  optimization_boundary:
    lower_boundary: [24, 25, 26]  # 对应3个空调的下边界
    upper_boundary: [28, 29, 30]  # 对应3个空调的上边界
  default_optimization_result: [25, 26, 27]  # 默认优化结果 